language: objective-c

before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - pod install
  - set -o pipefail && xcodebuild build -workspace Example/SatispayAppExtension.xcworkspace -scheme SatispayAppExtension-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' ONLY_ACTIVE_ARCH=NO | xcpretty
  - pod lib lint
